---
title: "README"
author: "Charles Rivera"
date: "2023-08-07"
output: html_document
---

# Water Primrose Project

> **Charles F. Rivera**, Bailey Morrison PhD, Erin L. Hestir PhD, School of Engineering, University of California, Merced

# Overview

Water primroses are one of the most invasive aquatic plants found throughout the world, and their presence brings about both environmental and economic consequences. To investigate the invasion strategies of this invasive plant, remote sensing plant spectroscopy can be employed.

The purpose of this code is to preprocess the water primrose spectral data collected between the summer of 2021 and spring of 2022 from the Sacramento-San Joaquin Delta, CA. The goal is to format the data in a way that is compatible with various analysis techniques and packages, such as HSDAR.

# Code

*spectral_csv_binder.Rmd*

> Accesses the csv files in the ASCII folders and concatenates them into one big csv file.

*spectral_plots_all.Rmd*

> Plots all samples for each season onto a pdf. Each plot contains the site codes and number

*wp_spectral_analysis.Rmd*

> -   Calculates summary statistics (mean, median, standard deviation, quartiles, etc) and uses the HSDAR package to calculate spectral comparison techniques (e.g euclidean distance and spectral angle mapper). Spectral comparison techniques can be used on the mean or median of the data (look at the parameters for the *comparison_technique* function). todo: summary plots
> -   At the bottom of this notebook, there is code to define which samples you want to remove from the data set given a specified range of row numbers. One way to use this is to look at the plots generated from the *spectral_plots_all.Rmd* notebook (e.g wp_summer_spectra_plots_WR.pdf) and take note of the plot numbers there.
> -   You will have to do this for the Spring 2022 data, as LATT1p_0522_0100000, LATT1p_0522_0100001, LATT1p_0522_0100002 have corrupted data. Their row numbers are already defined in notebook (463:465).

# Data

Change the file path in the read.csv function to the season you want to look at

```{r}
spectral_data = read.csv('/Users/charles/Desktop/wp_asd_spectra/wp_summer_2021/wp_summer.csv', sep=',', row.names=1)

# Get rid of the "X" in front of columns
updatedColumns <- colnames(spectral_data)
for (i in seq_along(updatedColumns)) {
  updatedColumns[i] <- substring(updatedColumns[i], 2)
}
colnames(spectral_data) <- updatedColumns

head(spectral_data)
```
